services:
  db:
    image: postgres:16
    container_name: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    expose:
      - 5432
    ports:
      - 5432:5432

volumes:
  pg-data:
